field: 09d7205f-7433-426c-9841-55969fd31a37
fieldLayouts:
  a5825b17-1f34-4fc8-a2b9-debe9da3f3a4:
    tabs:
      -
        elements:
          -
            fieldUid: e880a818-a810-4520-b994-20be1c852d01
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6562a881-8024-4fa6-9dec-b7b96dd13884
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fa278485-8621-43f6-91d1-7bb242499988
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a6c6621d-cb78-4a0f-8778-d15e8398aae7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 360d24d3-e966-4dad-a9c9-ee921bf28f22
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4bdb957f-8698-4eb4-9645-e82ed84aa2c7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  360d24d3-e966-4dad-a9c9-ee921bf28f22:
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: ''
    name: Spacing
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 1/3
            -
              - value
              - spacing-1-3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 2/3
            -
              - value
              - spacing-2-3
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  4bdb957f-8698-4eb4-9645-e82ed84aa2c7:
    contentColumnType: boolean
    fieldGroup: null
    handle: colored
    instructions: 'Should it be colored, or just black on white?'
    name: Colored
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  6562a881-8024-4fa6-9dec-b7b96dd13884:
    contentColumnType: text
    fieldGroup: null
    handle: citation
    instructions: ''
    name: Citation
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a6c6621d-cb78-4a0f-8778-d15e8398aae7:
    contentColumnType: string
    fieldGroup: null
    handle: alignment
    instructions: ''
    name: Alignment
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  e880a818-a810-4520-b994-20be1c852d01:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fa278485-8621-43f6-91d1-7bb242499988:
    contentColumnType: string
    fieldGroup: null
    handle: size
    instructions: ''
    name: Size
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - medium
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: blockquote
name: Blockquote
sortOrder: 3
