isPublic: true
name: 'Public Schema'
scope:
  - 'sections.5f25ab18-747e-406e-b86e-00d459c7faa9:read'
  - 'entrytypes.c8e82d53-afff-4dea-8df8-8954d011a04a:read'
  - 'volumes.ed7a90f0-b4e5-4c4c-b15c-831c22754213:read'
  - 'gatsby:read'
