enableVersioning: true
handle: about
name: About
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  35815072-acac-4452-9c5d-768772bc4940:
    enabledByDefault: true
    hasUrls: true
    template: about
    uriFormat: about
type: single
