enableVersioning: true
handle: stories
name: Stories
propagationMethod: all
siteSettings:
  35815072-acac-4452-9c5d-768772bc4940:
    enabledByDefault: true
    hasUrls: true
    template: stories/story
    uriFormat: 'stories/{slug}'
type: channel
