enableVersioning: true
handle: web
name: Web
propagationMethod: all
siteSettings:
  35815072-acac-4452-9c5d-768772bc4940:
    enabledByDefault: true
    hasUrls: true
    template: web/index
    uriFormat: web
type: single
